In [1]:
import h5py
import matplotlib.pyplot as plt
from pathlib import Path
import numpy as np
import pandas as pd

In [32]:
folder_path = './DATASET' # Replace with your folder path
# This creates a list of extensions (including the dot)
file_paths = [f for f in Path(folder_path).iterdir() if f.is_file() and f.suffix == '.hdf5']

df = None
data = []
for idx, file in enumerate(file_paths):
    layer_dict = {}
    file_info = h5py.File(file, 'r')
    file_data = file_info['OpenData']
    x = file_data[0]
    y = file_data[1]
    p = file_data[5]
    ir = file_data[6]
    c1 = file_data[9]
    c2 = file_data[10]
    id1 = file_data[7]
    id2 = file_data[8]
    
    layer_dict["file"] = file
    layer_dict["num_points"] = len(x)
    layer_dict["bulk_indicator"] = True if int(id1[0])== 1 else False
    layer_dict["first_3_post_anomaly"] = True if int(id1[0])== 1 else False
    layer_dict["min_x"] = x.min()
    layer_dict["max_x"] = x.max()
    layer_dict["min_y"] = y.min()
    layer_dict["max_y"] = y.max()

    if not isinstance(df, pd.DataFrame):
        df = pd.DataFrame(layer_dict, index=[idx])
    else:
        df = pd.concat([df, pd.DataFrame(layer_dict, index=[idx])])
#     #print(len(lazer))
#     #print(len(signal))
#     if len(x) != len(y):
#         print(f"There is an issue with {file}")
#     if len(x) < min_rows:
#         min_rows = len(x)
#     data.append([x, y, p, ir, c1, c2, id1, id2])
# print(f"The minimum number of data points in a single file is {min_rows}")

In [33]:
display(df)

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y
0,DATASET/layer331.hdf5,31100,True,True,-27.762575,-18.462799,-89.484657,-80.172905
1,DATASET/layer108.hdf5,30731,True,True,-27.765194,-18.462425,-89.482407,-80.173653
2,DATASET/layer151.hdf5,31087,True,True,-27.762199,-18.463549,-89.485031,-80.172531
3,DATASET/layer155.hdf5,30839,True,True,-27.764446,-18.463173,-89.482407,-80.172531
4,DATASET/layer209.hdf5,31133,True,True,-27.767815,-18.456062,-89.481293,-80.172905
...,...,...,...,...,...,...,...,...
374,DATASET/layer84.hdf5,31114,True,True,-27.761826,-18.463173,-89.483154,-80.172531
375,DATASET/layer157.hdf5,9679,False,False,-27.765194,-18.459057,-89.482040,-80.177399
376,DATASET/layer142.hdf5,30511,True,True,-27.767441,-18.458309,-89.480911,-80.174400
377,DATASET/layer244.hdf5,30704,True,True,-27.765944,-18.458309,-89.481293,-80.174026
378,DATASET/layer189.hdf5,30978,True,True,-27.764446,-18.461302,-89.482407,-80.174774

In [38]:
bulk = df[df["bulk_indicator"]==False]
bulk

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y
5,DATASET/layer272.hdf5,9720,False,False,-27.766317,-18.459431,-89.481293,-80.174400
16,DATASET/layer91.hdf5,9617,False,False,-27.764446,-18.463173,-89.485031,-80.172905
20,DATASET/layer306.hdf5,9641,False,False,-27.764446,-18.464670,-89.482407,-80.172531
21,DATASET/layer94.hdf5,31062,False,False,-27.763699,-18.463173,-89.483902,-80.172905
23,DATASET/layer305.hdf5,9707,False,False,-27.770809,-18.459431,-89.482040,-80.172905
...,...,...,...,...,...,...,...,...
355,DATASET/layer62.hdf5,30770,False,False,-27.764446,-18.461678,-89.483154,-80.174026
356,DATASET/layer90.hdf5,9672,False,False,-27.771931,-18.458683,-89.484283,-80.173279
360,DATASET/layer26.hdf5,9670,False,False,-27.770435,-18.458309,-89.482788,-80.174026
372,DATASET/layer308.hdf5,9560,False,False,-27.695583,-18.565344,-89.480537,-80.175148
375,DATASET/layer157.hdf5,9679,False,False,-27.765194,-18.459057,-89.482040,-80.177399

In [40]:
first_3 = df[df["first_3_post_anomaly"]==True]
first_3

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y
0,DATASET/layer331.hdf5,31100,True,True,-27.762575,-18.462799,-89.484657,-80.172905
1,DATASET/layer108.hdf5,30731,True,True,-27.765194,-18.462425,-89.482407,-80.173653
2,DATASET/layer151.hdf5,31087,True,True,-27.762199,-18.463549,-89.485031,-80.172531
3,DATASET/layer155.hdf5,30839,True,True,-27.764446,-18.463173,-89.482407,-80.172531
4,DATASET/layer209.hdf5,31133,True,True,-27.767815,-18.456062,-89.481293,-80.172905
...,...,...,...,...,...,...,...,...
373,DATASET/layer239.hdf5,30898,True,True,-27.763325,-18.463173,-89.483154,-80.173279
374,DATASET/layer84.hdf5,31114,True,True,-27.761826,-18.463173,-89.483154,-80.172531
376,DATASET/layer142.hdf5,30511,True,True,-27.767441,-18.458309,-89.480911,-80.174400
377,DATASET/layer244.hdf5,30704,True,True,-27.765944,-18.458309,-89.481293,-80.174026
378,DATASET/layer189.hdf5,30978,True,True,-27.764446,-18.461302,-89.482407,-80.174774

In [37]:
df["min_x"].round().unique()

array([-28.], dtype=float32)